search:
    pattern:        /search.{_format}
    defaults:       { _controller: KnpBundlesBundle:Bundle:search, _format: html }
    requirements:   { _method: "GET|POST", _format: "(html|json)" }

latest:
    pattern:        /latest.{_format}
    defaults:       { _controller: KnpBundlesBundle:Bundle:listLatest, _format: atom }
    requirements:   { _method: "GET", _format: atom }

add_bundle:
    pattern:        /add
    defaults:       { _controller: KnpBundlesBundle:Bundle:add }
    requirements:   { _method: "GET|POST" }

bundle_list:
    pattern:        /{sort}.{_format}
    defaults:       { _controller: KnpBundlesBundle:Bundle:list, sort: trend, _format: html }
    requirements:   { _method: "GET", sort: "(best|updated|newest|trend|recommended)", _format: "(html|json)" }

bundle_keyword:
    pattern:        /keyword/{slug}.{_format}
    defaults:       { _controller: KnpBundlesBundle:Bundle:searchByKeyword, _format: html }
    requirements:   { _method: "GET", _format: "(html|json)" }

bundle_change_usage_status:
    pattern:        /{ownerName}/{name}/change-usage-status
    defaults:       { _controller: KnpBundlesBundle:Bundle:changeUsageStatus }
    requirements:   { _method: "GET" }

bundle_get_badge_short:
    pattern:        /{ownerName}/{name}/badge-short
    defaults:       { _controller: KnpBundlesBundle:Badge:show, type: short }
    requirements:   { _method: "GET" }

bundle_get_badge:
    pattern:        /{ownerName}/{name}/badge
    defaults:       { _controller: KnpBundlesBundle:Badge:show }
    requirements:   { _method: "GET" }

bundle_show:
    pattern:        /{ownerName}/{name}.{_format}
    defaults:       { _controller: KnpBundlesBundle:Bundle:show, _format: html }
    requirements:   { _method: "GET", _format: "(html|json)" }

bundle_settings:
    pattern:        /bundle/settings/{id}
    defaults:       { _controller: KnpBundlesBundle:Bundle:settings }
    requirements:   { _method: "POST" }
