organizations_list:
    pattern:        /organization.{_format}
    defaults:       { _controller: KnpBundlesBundle:Organization:list, sort: name, _format: html }
    requirements:   { _method: "GET", _format: html|json }

organization_list:
    pattern:        /organization/{sort}.{_format}
    defaults:       { _controller: KnpBundlesBundle:Organization:list, sort: name, _format: html }
    requirements:   { _method: "GET", sort: "(name|developers|bundles)", _format: html|json }

organization_show:
    pattern:        /organization/{name}/profile.{_format}
    defaults:       { _controller: KnpBundlesBundle:Organization:show, _format: html }
    requirements:   { _method: "GET", _format: html|json }

organization_bundle_list:
    pattern:        /organization/{name}/bundles.{_format}
    defaults:       { _controller: KnpBundlesBundle:Organization:bundles, _format: json }
    requirements:   { _method: "GET", _format: json }

organization_members_list:
    pattern:        /organization/{name}/members.{_format}
    defaults:       { _controller: KnpBundlesBundle:Organization:members, _format: json }
    requirements:   { _method: "GET", _format: json }
