# @todo start deprecated route --> kept for seo but remove this route after some time
scoring:
    pattern: /about/scoring
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: faq_scoring
        permanent: true
# @todo end deprecated route --> kept for seo but remove this route after some time

faq_scoring:
    pattern:        /about/faq-scoring
    defaults:       { _controller: KnpBundlesBundle:Main:faqScoring }
    requirements:   { _method: "GET" }

api:
    pattern:        /api
    defaults:       { _controller: KnpBundlesBundle:Main:api }
    requirements:   { _method: "GET" }

evolution:
    pattern:        /evolution
    defaults:       { _controller: KnpBundlesBundle:Bundle:evolution }
    requirements:   { _method: "GET" }

symfony2bundles:
    pattern:        /symfony2bundles
    defaults:       { _controller: KnpBundlesBundle:Main:symfony2bundles }
    requirements:   { _method: "GET" }
