<?php

namespace Application\S2bBundle\Entities;

use Doctrine\ORM\EntityRepository;

/**
 * BundleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BundleRepository extends EntityRepository
{
}
