imports:
  - { resource: config.yml }

framework:
    esi: { enabled: true }

# KnpBundles Configuration
knp_bundles:
    github_client:
        limit:    %knp_bundles.github.limit%

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: critical
            handler: grouped
        grouped:
            type: group
            members:  [nested, buffered]
        nested:
            type: stream
            path: %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        buffered:
            type: buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: %monolog.swift.from_email%
            to_email:   %monolog.swift.to_email%
            subject:    "[ERROR] knpbundles.com"
            level:      debug

