imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

mink:
    show_cmd: firefox %s

doctrine:
    dbal:
        dbname:   %database_name%_test
