#!/usr/bin/env php
<?php

require_once __DIR__.'/S2bKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new S2bKernel('dev', true);

$application = new Application($kernel);
$application->run();
