<?php

namespace Knp\Bundle\Symfony2BundlesBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function findOneByName($name)
    {
        try {
            return $this->createQueryBuilder('u')
                ->where('u.name = :name')
                ->setParameter('name', $name)
                ->getQuery()
                ->getSingleResult();
        } catch(NoResultException $e) {
            return null;
        }
    }

    public function findOneByNameWithRepos($name)
    {
        try {
            return $this->createQueryBuilder('u')
                ->leftJoin('u.repos', 'r')
                ->leftJoin('u.contributionRepos', 'cr')
                ->where('u.name = :name')
                ->setParameter('name', $name)
                ->getQuery()
                ->getSingleResult();
        } catch(NoResultException $e) {
            return null;
        }
    }

    public function findAllSortedBy($field)
    {
        return $this->createQueryBuilder('u')
            ->orderBy('u.'.$field, 'name' === $field ? 'asc' : 'desc')
            ->getQuery()
            ->getResult();
    }

    public function findAllWithProjectsSortedBy($field)
    {
        return $this->queryAllWithProjectsSortedBy($field)->getResult();
    }

    public function queryAllWithProjectsSortedBy($field)
    {
        return $this->createQueryBuilder('u')
            ->orderBy('u.'.$field, 'name' === $field ? 'asc' : 'desc')
            ->leftJoin('u.repos', 'r')
            ->leftJoin('u.contributionRepos', 'cr')
            ->select('u, r, cr')
            ->getQuery();
    }

    public function count()
    {
        return $this->getEntityManager()->createQuery('SELECT COUNT(e.id) FROM '.$this->getEntityName().' e')->getSingleScalarResult();
    }
}
