<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120629202640 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        // this is only altering the table property
        /*
         * This SQL only alters the table by adding symfonyVersions property as array and
         * drops symfonyVersion old table field, we however have to force a complete
         * update of all bundles after this migration.
         */
        $this->addSql("ALTER TABLE bundle ADD symfonyVersions LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', DROP symfonyVersion");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE bundle ADD symfonyVersion VARCHAR(255) DEFAULT NULL, DROP symfonyVersions");
    }
}
