#!/usr/bin/env php
<?php

require_once __DIR__.'/S2bKernel.php';

use Symfony\Framework\FoundationBundle\Console\Application;

$kernel = new S2bKernel('prod', true);

$application = new Application($kernel);
$application->run();
