#!/usr/bin/env php
<?php

require_once __DIR__.'/FrontKernel.php';

use Symfony\Framework\WebBundle\Console\Application;

$kernel = new FrontKernel('dev', true);

$application = new Application($kernel);
$application->run();
